name: Maven Deploy CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build with Maven
        uses: actions/checkout@v1
        env:
          GITHUB_USERNAME: x-access-token
          GITHUB_TOKEN: c1700c3b1d9f0d6fab1e3e4ed6d898d7ae9cfbd8
      - run: |
          mvn deploy:deploy-file -Dregistry=https://maven.pkg.github.com/Avijit-07 -Dtoken=$GITHUB_TOKEN
